name: Deploy Node.js App

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up SSH and Deploy
        uses: appleboy/ssh-action@master
        with:
          host: 172.232.110.246  # Your server IP
          username: root     # Change this to your server's user
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /var/www/html/appscript/  # Change this to your app's path
            git pull origin main
            npm install
            pm2 stop server || true  
            pm2 start server.js --name "server"
            pm2 save
            pm2 restart server
            pm2 list
